### ISSUE TITLE
Error unpacking signature (using web3.eth.sign) 

### ISSUE THREAD

**Issue by bh2smith** [gnosis/safe-transaction-service#93]
**Describe the bug**

There seems to be some inconsistencies when sending a transaction signed using web3. That is, the Sender/Signer address derived from the signature appears to be coming from nowhere:

However, continuing to attempt the same transaction sometime yields the desired result.

For example, in https://github.com/gnosis/dex-liquidity-provision/pull/258 when trying to execute the **Test Plan** the we get the following error:

```
Signing and posting multi-send transaction 0x85939aa0f910ddbf5a672d5fd2e31b06c7a7f7976ac86ed51bab4d0e24f1e6b5 from proposer account 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1

Error: Error while talking to the gnosis-interface: {"nonFieldErrors":["Signer=0x274EEcF61F9c463467b33EF0db9A40De4Ee74FD5 is not an owner or delegate. Current owners=['0x7f01D9b227593E033bf8d6FC86e634d27aa85568', '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1']. Delegates=[]"]}
    at /Users/admin/Projects/gnosis/dex-liquidity-provision/scripts/utils/sign_and_send.js:80:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
1. Checkout this branch and install: https://github.com/gnosis/dex-liquidity-provision/pull/258 
2. Run

```sh
 export PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
npx truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=4 --lowestLimit=190 --highestLimit=210 --currentPrice=202 --masterSafe=0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce --depositBaseToken=0.1 --depositQuoteToken=10 --numBrackets=2 --network=rinkeby
```
3. Say yes to any "do you want to proceed" warnings.
4. Observe that one of the logs is 
```Using account: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1```
which is the intended POST sender.
5. Likely see the error above.

**Expected behavior**
We would expect that the sender is as specified and it seems like there is some problem unpacking the signature.

**Additional context**
Some useful snippets:

Our `POST` is made from here (using an unlocked web3 account)

https://github.com/gnosis/dex-liquidity-provision/blob/8a5b2a8848756b9a4d9ed61e3ce266a84be7e434/scripts/utils/sign_and_send.js#L59-L81

and the `getSafeCompatibleSignature` is here

https://github.com/gnosis/dex-liquidity-provision/blob/8a5b2a8848756b9a4d9ed61e3ce266a84be7e434/scripts/utils/internals.js#L177-L184

**Comment by rmeissner** [comment]
Could you add a complete example log when this happened (including the signer and complete post data). Also can you write a simple script/ test that can reproduce that issue (in your example there are to many "moving" parts, which make it hard for has to test this ;) )

If any of this data is sensible please submit it on slack

**Comment by bh2smith** [comment]
**Complete script for reproducibility** 
(note that this will be outdated as soon as the price of eth moves by 2% - I can't change that):

```sh
git clone git@github.com:gnosis/dex-liquidity-provision.git
cd dex-liquidity-provision
git checkout 235/PK_issue
yarn install
 export PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
npx truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=4 --lowestLimit=190 --highestLimit=210 --currentPrice=202 --masterSafe=0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce --depositBaseToken=0.1 --depositQuoteToken=10 --numBrackets=2 --network=rinkeby
```


**Complete Error message**

```
Using network 'rinkeby'.

Using account: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
==> Performing safety checks
==> Deploying 2 trading brackets
[HDWalletProvider] Using nonce:  16705
List of deployed brackets: 0x20026F06342e16415b070ae3bdB3983AF7c51C95,0xe95c569aB66f4EC6863776D3E88204242d660DB0
==> Building orders and deposits
Batch Exchange 0xC576eA7bd102F7E476368a5E98FA455d1Ea34dE2
Constructing bracket trading strategy order data between the limits 190-210 USDC per WETH
Safe 0 - 0x20026F06342e16415b070ae3bdB3983AF7c51C95:
  Buy  WETH with USDC at 190
  Sell WETH for  USDC at 199.7498435543818
Safe 1 - 0xe95c569aB66f4EC6863776D3E88204242d660DB0:
  Buy  WETH with USDC at 199.7498435543818
  Sell WETH for  USDC at 210.00000000000006
Transaction bundle size 4
==> Sending the order placing transaction to gnosis-safe interface.
    Attention: This transaction MUST be executed first!
Signing and posting multi-send transaction 0xe7e5ee18356fb556cb6565fc464bca743ae04ab6b0b0a63536362004d9eed14a from proposer account 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
Error: Error while talking to the gnosis-interface: {"nonFieldErrors":["Signer=0x687E48c0E04457e57c631A402706D70b1f49F137 is not an owner or delegate. Current owners=['0x7f01D9b227593E033bf8d6FC86e634d27aa85568', '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1']. Delegates=[]"]}
    at /Users/admin/Projects/gnosis/dex-liquidity-provision/scripts/utils/sign_and_send.js:89:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.27 (core: 5.1.27)
Node v10.17.0
```

Let me just highlight that the error is at the bottom and that this is not much different than what is contained in the issue description.

**Comment by rmeissner** [comment]
Again it would be nice to have an example independant of your project (as we do not want to debug your project ;) ). Best case would be a test case or a piece of isolated code :) 

Also the `POST` data is missing in your output (important here are the signatures sent to the service)

**Comment by bh2smith** [comment]
At this time, I can't provide an isolated code segment, but I can give you the post data. My guess is that the transaction data may not even be necessary. I hope this helps!


```js
{ 
  to: '0x8D29bE29923b68abfDD21e541b9374737B49cdAD',
  value: 0,
  data: '0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008e4004dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000dc7aa21885b82702fb410bcdcb79e2643fca465c000000000000000000000000000000000000000000000000000000000098968000dc7aa21885b82702fb410bcdcb79e2643fca465c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003846a7612020000000000000000000000008d29be29923b68abfdd21e541b9374737b49cdad00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001848d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000132004dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000098968000c576ea7bd102f7e476368a5e98fa455d1ea34de20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004447e7ef240000000000000000000000004dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b000000000000000000000000000000000000000000000000000000000098968000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000410000000000000000000000008990c564ec303c7b26d3d5556ef0910e58be08ce0000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000c778417e063141139fce010982780140aa0cd5ab00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000eb3d50384ca35624c3e9a86e522eadb4a372ff23000000000000000000000000000000000000000000000000016345785d8a000000eb3d50384ca35624c3e9a86e522eadb4a372ff23000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003846a7612020000000000000000000000008d29be29923b68abfdd21e541b9374737b49cdad00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001848d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000013200c778417e063141139fce010982780140aa0cd5ab00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000016345785d8a000000c576ea7bd102f7e476368a5e98fa455d1ea34de20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004447e7ef24000000000000000000000000c778417e063141139fce010982780140aa0cd5ab000000000000000000000000000000000000000000000000016345785d8a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000410000000000000000000000008990c564ec303c7b26d3d5556ef0910e58be08ce0000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  operation: 1,
  safeTxGas: 314890,
  baseGas: 0,
  gasPrice: 0,
  gasToken: '0x0000000000000000000000000000000000000000',
  refundReceiver: '0x0000000000000000000000000000000000000000',
  nonce: 4,
  contractTransactionHash: '0xd2f7db973bd90e1aa55af074182cdb3776424ba2d0b791dae6e0ecd0c0296075',
  sender: '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1',
  signature: '0x913108c89510eab9831bcb0b580a241a7b4c6bd04e97ea28806b6b7b360b1827374512c7f16978131b5844e0b21f3a499bd8d29c344e5cb40eee5d5791ca29b020' 
}
```

**Comment by Uxio0** [comment]
Hi @bh2smith... There's a typo somewhere. I get this signature:

`0x913108c89510eab9831bcb0b580a241a7b4c6bd04e97ea28806b6b7b360b1827374512c7f16978131b5844e0b21f3a499bd8d29c344e5cb40eee5d5791ca29b01b` (v=27)

I add 4, so `v=31`:

`0x913108c89510eab9831bcb0b580a241a7b4c6bd04e97ea28806b6b7b360b1827374512c7f16978131b5844e0b21f3a499bd8d29c344e5cb40eee5d5791ca29b01f`

For you it's `20` instead of `1f`

**Comment by bh2smith** [comment]
Yes, thanks @Uxio0! It appears we have missed some cases when making our "modified signature". Big win for today.

**Comment by Uxio0** [comment]
Good to hear that, you are welcome @bh2smith !
